navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    publish_filtered_gps: true
    broadcast_utm_transform: true
    zero_altitude: true
    yaw_offset: 1.5708
    magnetic_declination_radians: 0.004654