ekf_node:
  ros__parameters:
    
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom      

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true,  true, false]
    imu0_queue_size: 5
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
    #imu0_pose_rejection_threshold: 0.8
    #imu0_twist_rejection_threshold: 0.8
    #imu0_linear_acceleration_rejection_threshold: 0.8

    odom0: /odometry/gps
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false
    #odom0_pose_rejection_threshold: 0.8
    #odom0_twist_rejection_threshold: 0.8