/**:
  ros__parameters:    
    video_device: '/dev/video2'
    framerate: 30.0
    io_method: 'mmap'
    frame_id: 'camera_link'
    image_width: 640
    image_height: 480
    camera_name: 'camera'
    camera_info_url: 'package://usv_localization/config/usb_cam.yaml'
