orb_slam2_mono:
  ros__parameters:

    publish_point_cloud: false
    publish_pose: true
    publish_tf: false
    localize_only: true

    reset_map: false
    load_map: false
    map_file: map.bin

    pointcloud_frame_id: odom

    camera_frame_id: camera_link    
    camera_fps: 30
    load_calibration_from_cam: true
    camera_rgb_encoding: true

    min_num_kf_in_map: 5
    ThDepth: 40.0
    depth_map_factor: 1.0
    camera_baseline: 171.0
