image_width: 640
image_height: 480
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [542.34972,   0.     , 314.64508,
           0.     , 541.00872, 244.51829,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.099261, -0.055983, -0.001307, -0.005444, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [561.44531,   0.     , 310.98239,   0.     ,
           0.     , 562.15271, 243.35823,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
